### ISSUE TITLE
Decide on a build system.

### ISSUE THREAD

**Issue by deanberris** [cpp-netlib/netlib#1]
Pick at least one of:

- bazel
- CMake
- gn

for the build system.

**Comment by jamesjallorina** [comment]
Cmake please

**Comment by glynos** [comment]
I'm not familiar with bazel, but CMake today has really good tool integration (even if it's weird and sometimes difficult to use). gn doesn't seem to be as portable, nor does it seem to integrate with IDEs.

My feeling is that the question should be "why not CMake".

**Comment by deanberris** [comment]
No real objection to CMake, was just hoping to get a discussion going on whether we should also support other build systems that aren't CMake. :)

So it's CMake and... nothing else?

**Comment by jamesjallorina** [comment]
Maybe we can support other build systems in the future. But for the meantime we can start first with CMake. :)

**Comment by deanberris** [comment]
Oops -- wrong buttons. I think it's settled then, happy to stick to CMake for now. :)
